server {
    listen 80;
    server_name _;

    root /ros2_ws/src/my_robot/my_robot/web/static;
    index index.html;

    # gzip static assets
    gzip on;
    gzip_types text/css application/javascript;

    # Static files with cache headers
    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(css|js)$ {
        expires 1h;
        add_header Cache-Control "public, no-transform";
    }

    location /snapshot {
        proxy_pass  http://127.0.0.1:8080/snapshot;
        add_header  Cache-Control "no-store, no-cache";
    }

    # WebSocket
    location /ws {
        proxy_pass             http://127.0.0.1:8080/ws;
        proxy_http_version     1.1;
        proxy_set_header       Upgrade $http_upgrade;
        proxy_set_header       Connection "upgrade";
        proxy_read_timeout     3600s;
    }

    # REST API
    location /cmd/ {
        proxy_pass http://127.0.0.1:8080/cmd/;
    }

    location /gamepad/ {
        proxy_pass http://127.0.0.1:8080/gamepad/;
    }

    location /autopilot/ {
        proxy_pass http://127.0.0.1:8080/autopilot/;
    }

}
